version: '3.3'
services:
  parking:
    build: .
    volumes:
      # This volume is only for development
      - ./src:/usr/src
    ports:
      - 8000:3000
    environment:
      RAILS_ENV: development
      PARKINGAPI_DATABASE_USERNAME: postgres
      PARKINGAPI_DATABASE_PASSWORD: postgres
      PARKINGAPI_DATABASE_HOST: db
      PARKINGAPI_DATABASE_PORT: 5432
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - ./init-postgres-db.sh:/docker-entrypoint-initdb.d/init-postgres-db.sh
